# mlflow-pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---

# mlflow-pv
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mlflow-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mlflow
---

# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-app
  template:
    metadata:
      labels:
        app: mlflow-app
    spec:
      containers:
      - name: mlflow-app
        image: bibekyess/mlops-practice-mlflow:v2 # FIXME: Change with your docker-hub-username/repo-name:tag
        imagePullPolicy: Never
        args:
        - --host=0.0.0.0
        - --port=5000
        - --backend-store-uri=/opt/mlflow/backend/
        - --default-artifact-root=/opt/mlflow/artifacts/
        - --workers=2
        # Can also do this: (`--` seperates the command line arguments and is a common convention in docker container)
          # args: ["--host=0.0.0.0", "--port=5000", "--backend-store-uri=/opt/mlflow/backend/", "--default-artifact-root=/opt/mlflow/artifacts/", "--workers=2"]

        ports:
        - name: http
          containerPort: 5000
          protocol: TCP
        volumeMounts:
        - name: mlflow-pvc
          mountPath: /opt/mlflow/
      volumes:
        - name: mlflow-pvc
          persistentVolumeClaim:
            claimName: mlflow-pvc
---

# mlflow-service
apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
spec:
  selector:
    app: mlflow-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer  # Use "LoadBalancer" type to expose MLflow outside the cluster in Minikube
---

# mlflow-ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mlflow-ingress
  annotations:
    nginx.ingress.kubernetes.io/add-base-url: "true"
    cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer
    # cert-manager.io/privatekey-algorithm: RSA
    # cert-manager.io/privatekey-encoding: PKCS1
    # cert-manager.io/privatekey-rotationPolicy: Always
spec:
  # Add tls section
  tls:
    - hosts:
        - "local-server.com"
      secretName: local-server-tls
  ingressClassName: nginx
  rules:
  - host: local-server.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mlflow-service
            port:
              number: 5000

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer # name of the resource
metadata:
  # we dont need a namespace for the ClusterIssuer resource
  name: letsencrypt-cluster-issuer
spec:
  acme:
    email: bibekyessali@hotmail.com
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Name of a secret used to store the ACME account private key
      name: letsencrypt-private-key
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
    - http01:
        ingress:
          class: nginx
