apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gpt2-hpa
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1
    kind: Deployment
    name: gpt2-deployment
  targetCPUUtilizationPercentage: 80
