kind: ConfigMap
apiVersion: v1
metadata:
  name: {{.Values.configmap.name}}
  namespace: {{.Values.namespace}}
data:
  BG_COLOR: '#12181b'
  FONT_COLOR: '#FFFFFF'
  CUSTOM_HEADER: {{.Values.configmap.data.CUSTOM_HEADER}} # Good practice is to match how it looks like in the configmap
