apiVersion: v1
kind: Service
metadata:
  labels:
    name: gpt2-app
  name: dev-kustom-gpt2-service-v1
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    name: gpt2-app
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: gpt2-app
  name: dev-kustom-gpt2-deployment-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gpt2-app
  template:
    metadata:
      labels:
        name: gpt2-app
    spec:
      containers:
      - image: fastapi-mlflow-dev:v1
        imagePullPolicy: Never
        name: gpt2-container
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: 2
            memory: 2Gi
          requests:
            cpu: 2
            memory: 2Gi
        volumeMounts:
        - mountPath: /opt/mlflow/
          name: mlflow-pvc
      volumes:
      - name: mlflow-pvc
        persistentVolumeClaim:
          claimName: mlflow-pvc
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/add-base-url: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  labels:
    name: gpt2-app
  name: dev-kustom-gpt2-ingress-v1
spec:
  ingressClassName: nginx
  rules:
  - host: local-server
    http:
      paths:
      - backend:
          service:
            name: dev-kustom-gpt2-service-v1
            port:
              number: 8000
        path: /fastapi/dev(/|$)(.*)
        pathType: ImplementationSpecific
