app:
  name: gpt2-app
  replicaCount: 1
  env: dev
  image:
    repository: fastapi-mlflow
    tag: v1
    pullPolicy: Never
  containerPort: 8000

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 1
    memory: 1Gi

deployment:
  name: gpt2-deployment
  port: 8000

service:
  name: gpt2-service
  type: NodePort
  port: 8000

ingress:
  enabled: false

autoscaling:
  enabled: false
